# Generated by Django 4.2.7 on 2024-02-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='residence_images/')),
                ('nomResidence', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
